# Generated by Django 5.2.4 on 2025-07-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('local_afetado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_conteudo', models.CharField(choices=[('artigo', 'Artigo'), ('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=20)),
                ('descricao', models.TextField()),
                ('url_midia', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('descartado', 'Descartado'), ('coletado', 'Coletado'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstanciaToxica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('efeitoAmbiental', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('comum', 'Comum'), ('admin', 'Administrador')], default='comum', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteToxico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dispositivoeletronico')),
                ('substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substanciatoxica')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('nivel_contaminacao', models.CharField(max_length=100)),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pontocoleta')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoeletronico',
            name='componentes_toxicos',
            field=models.ManyToManyField(through='app.ComponenteToxico', to='app.substanciatoxica'),
        ),
        migrations.CreateModel(
            name='UsuarioPontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utilizacao', models.DateField()),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pontocoleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
