# Generated by Django 5.2.4 on 2025-07-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('efeitoAmbiental', models.TextField()),
                ('nivel_perigo', models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='componentetoxico',
            name='substancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substancia'),
        ),
        migrations.AlterField(
            model_name='dispositivoeletronico',
            name='componentes_toxicos',
            field=models.ManyToManyField(through='app.ComponenteToxico', to='app.substancia'),
        ),
        migrations.DeleteModel(
            name='SubstanciaToxica',
        ),
    ]
